In [7]:
import pandas as pd

In [11]:
dt = pd.read_csv('./customer_data.csv')

In [12]:
print(dt)

     CustomerID   Genre  Age  AnnualIncome  SpendingScore
0             1    Male   49            22             12
1             2  Female   56            41             25
2             3    Male   66            41             52
3             4    Male   69            35             85
4             5    Male   49            44            100
..          ...     ...  ...           ...            ...
195         196  Female   47            97             45
196         197  Female   55           125             77
197         198  Female   55           131              4
198         199    Male   62            83             62
199         200    Male   68           113             65

[200 rows x 5 columns]

In [13]:
dt.mean(numeric_only=True)

CustomerID       100.500
Age               44.405
AnnualIncome      81.215
SpendingScore     48.360
dtype: float64

In [15]:
dt.loc[:,'Age'].mean()

np.float64(44.405)

In [20]:
dt.loc[:,'AnnualIncome'].mean()

np.float64(81.215)

In [21]:
dt.mean(axis=1,numeric_only=True)[0:4]

0    21.00
1    31.00
2    40.50
3    48.25
dtype: float64

In [23]:
dt.median(numeric_only=True)

CustomerID       100.5
Age               46.0
AnnualIncome      80.5
SpendingScore     48.0
dtype: float64

In [24]:
dt.loc[:,'AnnualIncome'].median()

np.float64(80.5)

In [25]:
dt.median(axis=1,numeric_only=True)[0:4]

0    17.0
1    33.0
2    46.5
3    52.0
dtype: float64

In [26]:
dt.mode()

     CustomerID   Genre   Age  AnnualIncome  SpendingScore
0             1  Female  49.0         113.0           92.0
1             2    Male   NaN           NaN            NaN
2             3     NaN   NaN           NaN            NaN
3             4     NaN   NaN           NaN            NaN
4             5     NaN   NaN           NaN            NaN
..          ...     ...   ...           ...            ...
195         196     NaN   NaN           NaN            NaN
196         197     NaN   NaN           NaN            NaN
197         198     NaN   NaN           NaN            NaN
198         199     NaN   NaN           NaN            NaN
199         200     NaN   NaN           NaN            NaN

[200 rows x 5 columns]

In [27]:
dt.loc[:,'Age'].mode()

0    49
Name: Age, dtype: int64

In [28]:
dt.min()

CustomerID            1
Genre            Female
Age                  18
AnnualIncome         15
SpendingScore         1
dtype: object

In [29]:
dt.max()

CustomerID        200
Genre            Male
Age                69
AnnualIncome      149
SpendingScore     100
dtype: object

In [30]:
dt.loc[:,'Age'].min(skipna=False)

np.int64(18)

In [31]:
dt.loc[:,'Age'].max()

np.int64(69)

In [32]:
dt.std(numeric_only=True)

CustomerID       57.879185
Age              15.353816
AnnualIncome     38.864134
SpendingScore    28.791058
dtype: float64

In [33]:
dt.loc[:,'Age'].std()

np.float64(15.353816247657589)

In [34]:
dt.loc[:,'AnnualIncome'].std()

np.float64(38.86413358608403)

In [35]:
dt.std(axis=1,numeric_only=True)[0:4]

0    20.542639
1    23.108440
2    27.012343
3    36.123630
dtype: float64

In [37]:
dt.groupby(['Genre'])['Age'].mean()

Genre
Female    45.51
Male      43.30
Name: Age, dtype: float64

In [38]:
newdt=dt.rename(columns={'annual_income':'AnnualIncome'},inplace=False)

In [39]:
newdt

     CustomerID   Genre  Age  AnnualIncome  SpendingScore
0             1    Male   49            22             12
1             2  Female   56            41             25
2             3    Male   66            41             52
3             4    Male   69            35             85
4             5    Male   49            44            100
..          ...     ...  ...           ...            ...
195         196  Female   47            97             45
196         197  Female   55           125             77
197         198  Female   55           131              4
198         199    Male   62            83             62
199         200    Male   68           113             65

[200 rows x 5 columns]

In [40]:
from sklearn import preprocessing

In [41]:
en=preprocessing.OneHotEncoder()

In [42]:
en_dt=pd.DataFrame(en.fit_transform(dt[['Genre']]).toarray())

In [43]:
en_dt

       0    1
0    0.0  1.0
1    1.0  0.0
2    0.0  1.0
3    0.0  1.0
4    0.0  1.0
..   ...  ...
195  1.0  0.0
196  1.0  0.0
197  1.0  0.0
198  0.0  1.0
199  0.0  1.0

[200 rows x 2 columns]

In [44]:
dt_encode=newdt.join(en_dt)

In [45]:
dt_encode

     CustomerID   Genre  Age  AnnualIncome  SpendingScore    0    1
0             1    Male   49            22             12  0.0  1.0
1             2  Female   56            41             25  1.0  0.0
2             3    Male   66            41             52  0.0  1.0
3             4    Male   69            35             85  0.0  1.0
4             5    Male   49            44            100  0.0  1.0
..          ...     ...  ...           ...            ...  ...  ...
195         196  Female   47            97             45  1.0  0.0
196         197  Female   55           125             77  1.0  0.0
197         198  Female   55           131              4  1.0  0.0
198         199    Male   62            83             62  0.0  1.0
199         200    Male   68           113             65  0.0  1.0

[200 rows x 7 columns]